services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
volumes:
  node_modules:
