name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Log in to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract tags for Docker images
        id: docker-meta
        uses: docker/metadata-action@v3
        with:
          images: quay.io/aptible/reploy-ui

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: aptible/aptible-deploy-action@v1
        with:
          username: ${{secrets.APTIBLE_ROBOT_USERNAME}}
          password: ${{secrets.APTIBLE_ROBOT_PASSWORD}}
          app: 'reploy-ui'
          environment: 'aptible-production'
          docker_img: 'quay.io/aptible/reploy-ui'
