name: deploy

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract tags for Docker images
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: quay.io/aptible/cloud-ui

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            VITE_SENTRY_DSN=${{ secrets.PROD_SENTRY_DSN }}
            VITE_ORIGIN=app
            VITE_METRIC_TUNNEL_URL=https://metrictunnel-nextgen.aptible.com
            VITE_TUNA_ENABLED=true
            VITE_MINTLIFY_CHAT_KEY=${{ secrets.MINTLIFY_CHAT_KEY }}
            VITE_STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY }}
            VITE_FEATURE_BETA_ORG_IDS=${{ vars.FEATURE_BETA_ORG_IDS }}
            VITE_TOKEN_HEADER_ORG_IDS=${{ vars.TOKEN_HEADER_ORG_IDS }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: aptible/aptible-deploy-action@v4
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          app: 'app-ui'
          environment: 'aptible-production'
          docker_img: 'quay.io/aptible/cloud-ui:${{ github.ref_name }}'
          docker_repository_url: https://quay.io/repository/aptible/cloud-ui
          username: ${{ secrets.APTIBLE_ROBOT_USERNAME }}
          password: ${{ secrets.APTIBLE_ROBOT_PASSWORD }}
          private_registry_username:  ${{ secrets.DOCKER_USERNAME }}
          private_registry_password:  ${{ secrets.DOCKER_PASSWORD }}
