name: deploy

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract tags for Docker images
        id: docker-meta
        uses: docker/metadata-action@v3
        with:
          images: quay.io/aptible/cloud-ui

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
          build-args: |
            VITE_SENTRY_DSN=${{ secrets.VITE_SENTRY_DSN }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: aptible/aptible-deploy-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          app: 'cloud-ui'
          environment: 'aptible-production'
          docker_img: 'quay.io/aptible/cloud-ui:${{ github.ref_name }}'
          username: ${{ secrets.APTIBLE_ROBOT_USERNAME }}
          password: ${{ secrets.APTIBLE_ROBOT_PASSWORD }}
          private_registry_username:  ${{ secrets.DOCKER_USERNAME }}
          private_registry_password:  ${{ secrets.DOCKER_PASSWORD }}
